name: Docker Release

on:
  workflow_run:
    workflows: ["Release"]
    types: [completed]
  workflow_dispatch:
    inputs:
      release:
        description: "Release (e.g., 52f0348)"
        required: true

permissions:
  contents: read
  packages: write

jobs:
  docker-release:
    if: ${{ (github.event_name == 'workflow_dispatch' && github.ref_name == 'master') || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master') }}
    runs-on: ubuntu-latest
    env:
      RELEASE: ${{ github.event.inputs.release || github.event.workflow_run.head_sha }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.ref }}
          persist-credentials: false

      - name: Set release version
        run: |
          set -e
          if [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            echo "VERSION=${RELEASE:0:7}" >> "$GITHUB_ENV"
          else
            echo "VERSION=${RELEASE}" >> "$GITHUB_ENV"
          fi

      - name: Build Docker Images
        run: make VERSION=${VERSION} DOCKER=ghcr.io/${{ github.repository_owner }} GITHUB_REPO=${{ github.repository }} -f Makefile.docker release

      - name: Show Docker Images
        run: docker images

      - name: GHCR login
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2  # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker Images
        run: make VERSION=${VERSION} DOCKER=ghcr.io/${{ github.repository_owner }} GITHUB_REPO=${{ github.repository }} -f Makefile.docker docker-push
